events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Todo tráfico que llegue a la raíz (/) será enviado al servicio de Node.js
        location / {
            proxy_pass http://node-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
